# Generated by Django 4.2.6 on 2024-03-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_brand_en_product_brand_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at_ru',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=150, verbose_name='product_name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='product_name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='product_name'),
        ),
    ]
